#!/usr/bin/env bash
# live-bash-dance: __HEADING__
# Generated by __REPO__ (do not edit by hand).
#
# Usage:  curl -sL __URL__ | bash
#         curl -sL __URL__ | bash -s -- --color --loops 3
#
# This script only prints to your terminal. It makes no network calls,
# saves nothing and runs no eval. Read it before you pipe it. That's healthy.

# --- catalog (filled in by tools/build.mjs) ---
MODE=__MODE__
NAMES=(__NAMES__)
TITLES=(__TITLES__)
CREDITS=(__CREDITS__)
FPS=(__FPS__)
SIZES=(__SIZES__)

usage() {
  cat <<'USAGE'
options:
  --color       colour version (needs a 256-colour terminal)
  --loops N     play N times then exit (default: forever, Ctrl-C to stop)
  --fps N       override playback speed (1-60 frames per second)
  --width N     cap the width in columns (default: fit the terminal)
  --seconds N   with /all: seconds per animation (default 6)
  -h, --help    show this help
USAGE
}

# Largest size that fits cols x lines (one line kept for the footer); else the smallest.
pick_size() {
  local best="" s w h
  for s in $1; do
    w=${s%x*}; h=${s#*x}
    if [ "$w" -le "$2" ] && [ $((h + 1)) -le "$3" ]; then best=$s; fi
  done
  [ -n "$best" ] || best=${1%% *}
  printf '%s' "$best"
}

main() {
  local color=0 loops=0 fps_override=0 maxw=0 seconds=6
  while [ $# -gt 0 ]; do
    case "$1" in
      --color|--colour) color=1; shift ;;
      --loops) loops="${2-}"; shift 2 || shift ;;
      --fps) fps_override="${2-}"; shift 2 || shift ;;
      --width) maxw="${2-}"; shift 2 || shift ;;
      --seconds) seconds="${2-}"; shift 2 || shift ;;
      -h|--help) usage; return 0 ;;
      *) echo "unknown option: $1" >&2; usage >&2; return 2 ;;
    esac
  done
  local v
  for v in "$loops" "$fps_override" "$maxw" "$seconds"; do
    case "$v" in ''|*[!0-9]*) echo "numeric options need whole numbers" >&2; return 2 ;; esac
  done
  if [ "$fps_override" -gt 60 ]; then echo "--fps must be 1-60" >&2; return 2; fi
  [ "$seconds" -ge 1 ] || seconds=1

  local tty=0 cols=80 lines=1000
  if [ -t 1 ]; then
    tty=1
    cols=$(tput cols 2>/dev/null || echo 80)
    lines=$(tput lines 2>/dev/null || echo 24)
  fi
  if [ "$maxw" -gt 0 ] && [ "$maxw" -lt "$cols" ]; then cols=$maxw; fi

  # Which animations to play, and which size/colour section of each to load.
  local n=${#NAMES[@]} order=() i
  case "$MODE" in
    random) order=($((RANDOM % n))) ;;
    *) for ((i = 0; i < n; i++)); do order+=("$i"); done ;;
  esac
  local mode_word=plain
  [ "$color" -eq 1 ] && mode_word=color
  local want=() size
  for i in "${order[@]}"; do
    size=$(pick_size "${SIZES[$i]}" "$cols" "$lines")
    want[i]="$size $mode_word"
  done

  # Read only the wanted sections. FRAMES is flat; START/COUNT index into it.
  local FRAMES=() START=() COUNT=() frame="" line cur=-1 take=0
  while IFS= read -r line; do
    case "$line" in
      "@@ANIM "*"@@"|"@@SIZE "*"@@")
        if [ "$take" -eq 1 ] && [ -n "$frame" ]; then FRAMES+=("$frame"); COUNT[cur]=$((COUNT[cur] + 1)); fi
        frame=""; take=0
        case "$line" in
          "@@ANIM "*) line=${line#@@ANIM }; cur=${line%@@} ;;
          *) line=${line#@@SIZE }; line=${line%@@}
             if [ -n "${want[cur]-}" ] && [ "$line" = "${want[cur]}" ]; then
               take=1; START[cur]=${#FRAMES[@]}; COUNT[cur]=0
             fi ;;
        esac ;;
      "@@FRAME@@")
        if [ "$take" -eq 1 ]; then FRAMES+=("$frame"); COUNT[cur]=$((COUNT[cur] + 1)); fi
        frame="" ;;
      *) if [ "$take" -eq 1 ]; then frame+="$line"$'\n'; fi ;;
    esac
  done <<'CATALOG_EOF'
__CATALOG__
CATALOG_EOF
  if [ "$take" -eq 1 ] && [ -n "$frame" ]; then FRAMES+=("$frame"); COUNT[cur]=$((COUNT[cur] + 1)); fi

  # Not a terminal (piped to a file, etc.): print one frame and stop.
  if [ "$tty" -eq 0 ]; then
    printf '%b' "${FRAMES[${START[${order[0]}]}]}"
    return 0
  fi

  local w=${want[${order[0]}]%%x*}
  if [ "$w" -gt "$cols" ]; then
    printf 'Your terminal is %s columns wide; the smallest version needs %s. Widen it or zoom out.\n' "$cols" "$w"
    sleep 2
  fi

  # Alternate screen + hidden cursor; always restore on exit or Ctrl-C.
  restore() { printf '\033[0m\033[?25h\033[?1049l'; }
  trap 'trap - EXIT; restore; exit 130' INT TERM
  trap restore EXIT
  printf '\033[?1049h\033[?25l'

  local pass=0 pos fps ms delay steps s footer
  while :; do
    pos=0
    for i in "${order[@]}"; do
      pos=$((pos + 1))
      fps=${FPS[i]}
      [ "$fps_override" -gt 0 ] && fps=$fps_override
      ms=$((1000 / fps))
      delay="$((ms / 1000)).$(printf '%03d' $((ms % 1000)))"
      footer="  ${TITLES[i]}"
      [ "$MODE" = all ] && footer="$footer  ($pos/${#order[@]})"
      footer="$footer  -  ${CREDITS[i]}  -  Ctrl-C to stop"
      footer=${footer:0:cols-1}
      # One pass of the clip, or a time slot in /all mode.
      steps=${COUNT[i]}
      if [ "$MODE" = all ] && [ $((seconds * fps)) -gt "$steps" ]; then steps=$((seconds * fps)); fi
      printf '\033[0m\033[2J'
      for ((s = 0; s < steps; s++)); do
        printf '\033[H%b\033[0m%s' "${FRAMES[START[i] + s % COUNT[i]]}" "$footer"
        sleep "$delay"
      done
    done
    pass=$((pass + 1))
    if [ "$loops" -gt 0 ] && [ "$pass" -ge "$loops" ]; then break; fi
  done
}

# Everything runs from here, so a half-downloaded script does nothing.
main "$@"
