# live-bash-dance: __HEADING__
# Generated by __REPO__ (do not edit by hand).
#
# Usage (Windows PowerShell 5.1+ or PowerShell 7 on any OS):
#   irm __URL__.ps1 | iex
#   & ([scriptblock]::Create((irm __URL__.ps1))) -Color -Loops 3
#
# This script only prints to your terminal. It makes no network calls,
# saves nothing and runs no other code. Read it before you run it.

param(
  [switch]$Color,
  [int]$Loops = 0,
  [int]$Fps = 0,
  [int]$Width = 0,
  [int]$Seconds = 6
)

$Mode = '__MODE__'
$Names = @(__NAMES__)
$Titles = @(__TITLES__)
$Credits = @(__CREDITS__)
$FpsList = @(__FPS__)
$Sizes = @(__SIZES__)

$Catalog = @'
__CATALOG__
'@

function Select-Size([string]$list, [int]$cols, [int]$rows) {
  $all = $list.Split(' ')
  $best = $null
  foreach ($s in $all) {
    $w, $h = $s.Split('x') | ForEach-Object { [int]$_ }
    if ($w -le $cols -and ($h + 1) -le $rows) { $best = $s }
  }
  if ($null -eq $best) { $best = $all[0] }
  $best
}

$redirected = [Console]::IsOutputRedirected
$cols = 80; $rows = 1000
if (-not $redirected) {
  try { $cols = [Console]::WindowWidth; $rows = [Console]::WindowHeight } catch { $cols = 80; $rows = 24 }
}
if ($Width -gt 0 -and $Width -lt $cols) { $cols = $Width }
if ($Seconds -lt 1) { $Seconds = 1 }

if ($Mode -eq 'random') { $order = @(Get-Random -Maximum $Names.Count) }
else { $order = @(0..($Names.Count - 1)) }

$modeWord = if ($Color) { 'color' } else { 'plain' }
$want = @{}
foreach ($i in $order) { $want[$i] = "$(Select-Size $Sizes[$i] $cols $rows) $modeWord" }

# Read only the wanted sections into per-animation frame lists.
$esc = [string][char]27
$frames = @{}
$cur = -1; $take = $false
$sb = New-Object System.Text.StringBuilder
# Dot-sourced (". $pushFrame") so it runs in this scope however the script was started.
$pushFrame = {
  if ($take -and $sb.Length -gt 0) { $frames[$cur].Add($sb.ToString()) }
  [void]$sb.Clear()
}
foreach ($line in $Catalog -split "`r?`n") {
  if ($line.StartsWith('@@ANIM ')) {
    . $pushFrame; $take = $false
    $cur = [int]$line.Substring(7).TrimEnd('@')
  } elseif ($line.StartsWith('@@SIZE ')) {
    . $pushFrame
    $key = $line.Substring(7).TrimEnd('@')
    $take = $want.ContainsKey($cur) -and $want[$cur] -eq $key
    if ($take) { $frames[$cur] = New-Object System.Collections.Generic.List[string] }
  } elseif ($line -eq '@@FRAME@@') {
    . $pushFrame
  } elseif ($take) {
    [void]$sb.Append($line.Replace('\033', $esc)).Append("`n")
  }
}
. $pushFrame

if ($redirected) {
  [Console]::Out.Write($frames[$order[0]][0])
  return
}

$first = [int]($want[$order[0]].Split('x')[0])
if ($first -gt $cols) {
  Write-Host "Your terminal is $cols columns wide; the smallest version needs $first. Widen it or zoom out."
  Start-Sleep -Seconds 2
}

$cursor = $true
try { $cursor = [Console]::CursorVisible } catch { }
try {
  try { [Console]::CursorVisible = $false } catch { }
  $pass = 0
  while ($true) {
    $pos = 0
    foreach ($i in $order) {
      $pos++
      $rate = if ($Fps -gt 0) { [Math]::Min($Fps, 60) } else { $FpsList[$i] }
      $delay = [int](1000 / $rate)
      $footer = "  $($Titles[$i])"
      if ($Mode -eq 'all') { $footer += "  ($pos/$($order.Count))" }
      $footer += "  -  $($Credits[$i])  -  Ctrl-C to stop"
      if ($footer.Length -ge $cols) { $footer = $footer.Substring(0, [Math]::Max(0, $cols - 1)) }
      $list = $frames[$i]
      $steps = $list.Count
      if ($Mode -eq 'all' -and $Seconds * $rate -gt $steps) { $steps = $Seconds * $rate }
      [Console]::Clear()
      for ($s = 0; $s -lt $steps; $s++) {
        [Console]::SetCursorPosition(0, 0)
        [Console]::Out.Write($list[$s % $list.Count] + "$esc[0m" + $footer)
        Start-Sleep -Milliseconds $delay
      }
    }
    $pass++
    if ($Loops -gt 0 -and $pass -ge $Loops) { break }
  }
} finally {
  [Console]::Out.Write("$esc[0m")
  try { [Console]::CursorVisible = $cursor } catch { }
  [Console]::Clear()
}
